name: RT-Thread_Packages

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  # Runs at 00:00 UTC on the 1, 16 and 31th of every month
  schedule:
    - cron:  '0 0 */15 * *'
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  # This workflow contains a single job called "build"
  build:
      # The type of runner that the job will run on
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Set up Python
          uses: actions/setup-python@v3
          with:
            python-version: 3.8
        
        - name: Install Tools
          shell: bash
          run: |
            sudo apt-get update && sudo apt-get install python-tk
            sudo apt-get install scons rxvt-unicode
            sudo apt-get -qq install gcc-multilib libc6:i386 libgcc1:i386 gcc-4.6-base:i386 libstdc++5:i386 libstdc++6:i386 libsdl-dev || true
            pip install scons requests tqdm wget html-table

        - name: Packages check 
          shell: bash 
          run: |
            BASE_ROOT=${{ github.workspace }} && cd .. && mkdir packages_temp && cp packages -R packages_temp && mv packages_temp packages && cd packages/packages_temp  && echo "source \"\$PKGS_DIR/packages/Kconfig\"" > Kconfig
            cd ${BASE_ROOT} && export PKGS_ROOT=${BASE_ROOT}/packages_temp && git clone --depth=1 --branch=master https://github.com/RT-Thread/rt-thread.git rt-thread && export RTT_ROOT=${BASE_ROOT}/rt-thread || true
            cd ${RTT_ROOT}/tools/kconfig-frontends && scons || true
            export TERM=xterm
            cd ${RTT_ROOT}/bsp/qemu-vexpress-a9 && sudo -E ../../tools/kconfig-frontends/kconfig-mconf Kconfig -n
            cp ${RTT_ROOT}/tools/kconfiglib.py ./ && python -c 'import kconfiglib; kconfiglib.standard_kconfig()'
            cd ${PKGS_ROOT}/packages && python ci.py

        - name: Packages test
          shell: bash 
          run: |
            BASE_ROOT=${{ github.workspace }}
            cd .. && mkdir packages_temp && cp packages -R packages_temp && mv packages_temp packages/packages_temp && cd packages/packages_temp  && echo "source \"\$PKGS_DIR/packages/Kconfig\"" > Kconfig && cd .. && mkdir env && mv packages_temp env/packages
            cp env/* ~/.env/ -rf
            cd ${BASE_ROOT} && git clone https://github.com/RT-Thread/pkgs-test.git
            cd pkgs-test
            python -c 'import PackagesWarehouse; checkout=PackagesWarehouse.PackagesWarehouse("'${BASE_ROOT}/env/packages/packages'","https://github.com/RT-Thread/packages", "master"); checkout.write_config(checkout.get_change_pkg_name(),"config.json","git_config.json");'
            python pkgs-test.py --config=git_config.json
        - uses: actions/upload-artifact@v3
          with:
            name: artifacts_export
            path: ${{ github.workspace }}/pkgs-test/artifacts_export
